title: Annn V's Blog
author: Annn
email: annnv2018@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  Annn V's Blog, a blog as a result of learning GitHub Pages.
  Hello World!
  :D

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
